return {
	pde = {
		ai = false,
		angular = false,
		cpp = false,
		csharp = false,
		docker = false,
		elixir = false,
		flutter = false,
		go = false,
		html = false,
		java = false,
		json = false,
		julia = false,
		jupyter = false,
		kotlin = false,
		lua = true,
		python = true,
		r = false,
		react = true,
		ruby = false,
		rust = true,
		scala = true,
		solidity = false,
		svelte = false,
		tailwind = false,
		terraform = true,
		typescript = false,
		vuejs = false,
	},
}
